### ISSUE TITLE
error: lvalue required as left operand of assignment while installing on ubuntu.

### ISSUE THREAD

**Issue by changjej** [mehcode/python-xmlsec#6]
```
error: lvalue required as left operand of assignment

Installing collected packages: pyyaml, boto, peewee, couchbase, bottle, markupsafe, jinja2, beaker, idna, pyasn1, six, pycparser, cffi, cryptography, pyopenssl, lxml, xmlsec, isodate, python3-saml, filechunkio, python-dateutil, pytz, raven, pymysql, cherrypy
  Running setup.py install for xmlsec
    Complete output from command /webapplication/venv/pancake/bin/python3 -c "import setuptools, tokenize;__file__='/tmp/pip-build-aijzb_28/xmlsec/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-41kah7g8-record/install-record.txt --single-version-externally-managed --compile --install-headers /webapplication/venv/pancake/include/site/python3.4/xmlsec:
    running install
    running build
    running build_py
    running build_ext
    skipping 'src/xmlsec/constants.c' Cython extension (up-to-date)
    skipping 'src/xmlsec/utils.c' Cython extension (up-to-date)
    skipping 'src/xmlsec/tree.c' Cython extension (up-to-date)
    skipping 'src/xmlsec/key.c' Cython extension (up-to-date)
    skipping 'src/xmlsec/ds.c' Cython extension (up-to-date)
    skipping 'src/xmlsec/enc.c' Cython extension (up-to-date)
    building 'xmlsec.enc' extension
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -fPIC -DXMLSEC_NO_SIZE_T= -DXMLSEC_NO_GOST=1 -DXMLSEC_CRYPTO=openssl -DXMLSEC_CRYPTO_OPENSSL=1 -DXMLSEC_OPENSSL_098=1 -D__XMLSEC_FUNCTION__=__FUNCTION__ -DXMLSEC_NO_CRYPTO_DYNAMIC_LOADING=1 -DXMLSEC_NO_XKMS=1 -Isrc -I/webapplication/venv/pancake/lib/python3.4/site-packages/lxml/includes -I/webapplication/venv/pancake/lib/python3.4/site-packages/lxml -I/usr/include/libxml2 -I/usr/include/xmlsec1 -I/usr/include/python3.4m -I/webapplication/venv/pancake/include/python3.4m -c src/xmlsec/enc.c -o build/temp.linux-x86_64-3.4/src/xmlsec/enc.o -DXMLSEC_CRYPTO_OPENSSL=1
    src/xmlsec/enc.c: In function ‘__pyx_import_star_set’:
    src/xmlsec/enc.c:3384:37: error: lvalue required as left operand of assignment
         XMLSEC_ENC_RETURN_REPLACED_NODE = __Pyx_PyInt_As_unsigned_int(o); if ((XMLSEC_ENC_RETURN_REPLACED_NODE == (unsigned int)-1) && PyErr_Occurred()) {__pyx_filename = __pyx_f[2]; __pyx_lineno = 8; __pyx_clineno = __LINE__; goto __pyx_L2_error;};
                                         ^
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
```

I'm trying to install xmlsec==0.3.1 via `pip install xmlsec`, however, it fails with the previous errors. 

I already installed libxml2-dev and libxmlsec1-dev as the instruction. 

How can I install it?

**Comment by mehcode** [comment]
Can you tell me more about your environment? What OS are you on? What version of gcc do you have: `gcc --version`?

**Comment by zqad** [comment]
I had the same problem on Fedora 22;
`gcc (GCC) 5.1.1 20150618 (Red Hat 5.1.1-4)`

The problem went away after I moved the definition of `XMLSEC_ENC_RETURN_REPLACED_NODE` out from the `cdef extern from "xmlsec.h":`-block and made it a `cdef` of its own in `src/xmlsec/enc.pxd`:

```patch
diff --git a/src/xmlsec/enc.pxd b/src/xmlsec/enc.pxd
index 2de629b..740bbc7 100644
--- a/src/xmlsec/enc.pxd
+++ b/src/xmlsec/enc.pxd
@@ -2,11 +2,10 @@ from lxml.includes.tree cimport xmlChar, const_xmlChar, xmlNode
 from .key cimport xmlSecKeyPtr, xmlSecKeyReqPtr, xmlSecKeysMngrPtr
 from .ds cimport const_xmlSecByte, xmlSecBufferPtr
 
+cdef unsigned int XMLSEC_ENC_RETURN_REPLACED_NODE
 
 cdef extern from "xmlsec.h":  # xmlsec/keys.h
 
-    unsigned int XMLSEC_ENC_RETURN_REPLACED_NODE
-
     cdef struct _xmlSecEncCtx:
         # void * userData
         unsigned int flags```

Since I am not that familiar with Cython, I'm not sure that this is the correct way of solving the issue.

**Comment by mehcode** [comment]
@zqad or @changjej Could you submit a PR for that? I'll give it a go on my machines.

**Comment by changjej** [comment]
Sorry for late. 

I'm using Ubuntu 14.04.2 LTS on Docker Contianer and `gcc --version` is gcc (Ubuntu 4.8.2-19ubuntu1) 4.8.2.

@zqad I tried the it and it resolved the issue however, I have new problem. 

```
 Running setup.py install for xmlsec
    Complete output from command /venv/web/bin/python3 -c "import setuptools, tokenize;__file__='/tmp/pip-xtabe7he-build/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-zmgskd6t-record/install-record.txt --single-version-externally-managed --compile --install-headers /venv/web/include/site/python3.4/xmlsec:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.4
    creating build/lib.linux-x86_64-3.4/xmlsec
    copying src/xmlsec/__init__.py -> build/lib.linux-x86_64-3.4/xmlsec
    copying src/xmlsec/meta.py -> build/lib.linux-x86_64-3.4/xmlsec
    copying src/xmlsec/error.py -> build/lib.linux-x86_64-3.4/xmlsec
    running build_ext
    cythoning src/xmlsec/constants.pyx to src/xmlsec/constants.c
    building 'xmlsec.constants' extension
    creating build/temp.linux-x86_64-3.4
    creating build/temp.linux-x86_64-3.4/src
    creating build/temp.linux-x86_64-3.4/src/xmlsec
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -fPIC -D__XMLSEC_FUNCTION__=__FUNCTION__ -DXMLSEC_NO_XKMS=1 -DXMLSEC_NO_CRYPTO_DYNAMIC_LOADING=1 -DXMLSEC_NO_SIZE_T= -DXMLSEC_CRYPTO=openssl -DXMLSEC_OPENSSL_098=1 -DXMLSEC_CRYPTO_OPENSSL=1 -DXMLSEC_NO_GOST=1 -Isrc -I/venv/web/lib/python3.4/site-packages/lxml/includes -I/venv/web/lib/python3.4/site-packages/lxml -I/usr/include/xmlsec1 -I/usr/include/libxml2 -I/usr/include/python3.4m -I/venv/web/include/python3.4m -c src/xmlsec/constants.c -o build/temp.linux-x86_64-3.4/src/xmlsec/constants.o -DXMLSEC_CRYPTO_OPENSSL=1
    src/xmlsec/constants.c: In function ‘PyInit_constants’:
    src/xmlsec/constants.c:2419:61: error: ‘xmlSecTransformEcdsaSha1Id’ undeclared (first use in this function)
       __pyx_t_2 = ((PyObject *)__pyx_f_6xmlsec_9constants__mkti(xmlSecTransformEcdsaSha1Id)); if (unlikely(!__pyx_t_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 105; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
                                                                 ^
    src/xmlsec/constants.c:2419:61: note: each undeclared identifier is reported only once for each function it appears in
    src/xmlsec/constants.c:2431:61: error: ‘xmlSecTransformEcdsaSha224Id’ undeclared (first use in this function)
       __pyx_t_2 = ((PyObject *)__pyx_f_6xmlsec_9constants__mkti(xmlSecTransformEcdsaSha224Id)); if (unlikely(!__pyx_t_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 106; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
                                                                 ^
    src/xmlsec/constants.c:2443:61: error: ‘xmlSecTransformEcdsaSha256Id’ undeclared (first use in this function)
       __pyx_t_2 = ((PyObject *)__pyx_f_6xmlsec_9constants__mkti(xmlSecTransformEcdsaSha256Id)); if (unlikely(!__pyx_t_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 107; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
                                                                 ^
    src/xmlsec/constants.c:2455:61: error: ‘xmlSecTransformEcdsaSha384Id’ undeclared (first use in this function)
       __pyx_t_2 = ((PyObject *)__pyx_f_6xmlsec_9constants__mkti(xmlSecTransformEcdsaSha384Id)); if (unlikely(!__pyx_t_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 108; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
                                                                 ^
    src/xmlsec/constants.c:2467:61: error: ‘xmlSecTransformEcdsaSha512Id’ undeclared (first use in this function)
       __pyx_t_2 = ((PyObject *)__pyx_f_6xmlsec_9constants__mkti(xmlSecTransformEcdsaSha512Id)); if (unlikely(!__pyx_t_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 109; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
                                                                 ^
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    
    ----------------------------------------
    Command "/venv/web/bin/python3 -c "import setuptools, tokenize;__file__='/tmp/pip-xtabe7he-build/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-zmgskd6t-record/install-record.txt --single-version-externally-managed --compile --install-headers /venv/web/include/site/python3.4/xmlsec" failed with error code 1 in /tmp/pip-xtabe7he-build
```

**Comment by Nastya-Kruglikova** [comment]
Using Cython 0.23 instead of 0.23.1 helped me.

**Comment by zqad** [comment]
@Nastya-Kruglikova, well spotted.
I tried the patched version (i.e. @changjej 's PR) with Cython 0.23 (I used 0.23.1 earlier) as well, and it seem to work fine. So merging it should not introduce a regression but rather make it work in both Cython 0.23 and 0.23.1.

**Comment by mehcode** [comment]
Thanks @changjej and @bgaifullin! Sorry it took so long for me to get to this. This has been merged in and released as v0.3.3.
