### ISSUE TITLE
Install fails docker python:3.8-slim-buster

### ISSUE THREAD

**Issue by andormarkus** [mehcode/python-xmlsec#170]
Hi All,

I tried to install on python:3.8-slim-buster docker image but it fails with `ERROR: Could not build wheels for xmlsec which use PEP 517 and cannot be installed directly`.

Thanks,
Andor

<br><br>
My dockerfile
```dockerfile
FROM python:3.8-slim-buster

USER root

RUN apt-get update \
  && apt-get install -y \
         libxml2-dev \
         libxmlsec1-dev \
         libxmlsec1-openssl \
         pkg-config

RUN apt-get update

RUN pip install --upgrade pip setuptools wheel
RUN pip install xmlsec
```
<br><br>
Result of `pkg-config --cflags xmlsec1`
```bash
root@768d3ada0fb8:/# pkg-config --cflags xmlsec1
-D__XMLSEC_FUNCTION__=__func__ -DXMLSEC_NO_SIZE_T -DXMLSEC_NO_GOST=1 -DXMLSEC_NO_GOST2012=1 -DXMLSEC_NO_CRYPTO_DYNAMIC_LOADING=1 -DXMLSEC_CRYPTO_OPENSSL=1 -I/usr/include/xmlsec1 -I/usr/include/libxml2
```

<br><br>
version of `libxmlsec1`
```bash
root@768d3ada0fb8:/# apt list | grep libxmlsec1
libxmlsec1-dev/stable,now 1.2.27-2 amd64 [installed]
libxmlsec1-doc/stable 1.2.27-2 all
libxmlsec1-gcrypt/stable,now 1.2.27-2 amd64 [installed,automatic]
libxmlsec1-gnutls/stable,now 1.2.27-2 amd64 [installed,automatic]
libxmlsec1-nss/stable,now 1.2.27-2 amd64 [installed,automatic]
libxmlsec1-openssl/stable,now 1.2.27-2 amd64 [installed]
libxmlsec1/stable,now 1.2.27-2 amd64 [installed,automatic]
```

<br><br>
version of `libxml2`
```bash
root@768d3ada0fb8:/# apt list | grep libxml2
libxml2-dbg/stable 2.9.4+dfsg1-7+deb10u1 amd64
libxml2-dev/stable,now 2.9.4+dfsg1-7+deb10u1 amd64 [installed]
libxml2-doc/stable 2.9.4+dfsg1-7+deb10u1 all
libxml2-utils/stable 2.9.4+dfsg1-7+deb10u1 amd64
libxml2/stable,now 2.9.4+dfsg1-7+deb10u1 amd64 [installed,automatic]
python-libxml2-dbg/stable 2.9.4+dfsg1-7+deb10u1 amd64
python-libxml2/stable 2.9.4+dfsg1-7+deb10u1 amd64
python3-libxml2-dbg/stable 2.9.4+dfsg1-7+deb10u1 amd64
python3-libxml2/stable 2.9.4+dfsg1-7+deb10u1 amd64
```

<br><br>
Error log:
```bash
> [5/5] RUN pip install xmlsec:                                                                                                                                                                           
#8 0.755 Collecting xmlsec                                                                                                                                                                                 
#8 0.887   Downloading xmlsec-1.3.10.tar.gz (62 kB)                                                                                                                                                        
#8 1.071   Installing build dependencies: started                                                                                                                                                          
#8 3.996   Installing build dependencies: finished with status 'done'                                                                                                                                      
#8 4.004   Getting requirements to build wheel: started
#8 4.244   Getting requirements to build wheel: finished with status 'done'
#8 4.384   Installing backend dependencies: started
#8 8.306   Installing backend dependencies: finished with status 'done'
#8 8.311     Preparing wheel metadata: started
#8 8.696     Preparing wheel metadata: finished with status 'done'
#8 9.109 Collecting lxml>=3.8
#8 9.131   Using cached lxml-4.6.3-cp38-cp38-manylinux2014_x86_64.whl (6.8 MB)
#8 9.181 Building wheels for collected packages: xmlsec
#8 9.182   Building wheel for xmlsec (PEP 517): started
#8 9.486   Building wheel for xmlsec (PEP 517): finished with status 'error'
#8 9.487   ERROR: Command errored out with exit status 1:
#8 9.487    command: /usr/local/bin/python /usr/local/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py build_wheel /tmp/tmp3tlzj9ns
#8 9.487        cwd: /tmp/pip-install-_z5f5co9/xmlsec_43cfa5972a2944a8b155fbf9e117176b
#8 9.487   Complete output (27 lines):
#8 9.487   running bdist_wheel
#8 9.487   running build
#8 9.487   running build_py
#8 9.487   /tmp/pip-build-env-ryr0mnn_/overlay/lib/python3.8/site-packages/setuptools/dist.py:669: UserWarning: Usage of dash-separated 'description-file' will not be supported in future versions. Please use the underscore name 'description_file' instead
#8 9.487     warnings.warn(
#8 9.487   /tmp/pip-build-env-ryr0mnn_/overlay/lib/python3.8/site-packages/setuptools/dist.py:669: UserWarning: Usage of dash-separated 'build-requires' will not be supported in future versions. Please use the underscore name 'build_requires' instead
#8 9.487     warnings.warn(
#8 9.487   /tmp/pip-build-env-ryr0mnn_/overlay/lib/python3.8/site-packages/setuptools/dist.py:669: UserWarning: Usage of dash-separated 'upload-dir' will not be supported in future versions. Please use the underscore name 'upload_dir' instead
#8 9.487     warnings.warn(
#8 9.487   package init file 'src/xmlsec/__init__.py' not found (or not a regular file)
#8 9.487   creating build
#8 9.487   creating build/lib.linux-x86_64-3.8
#8 9.487   creating build/lib.linux-x86_64-3.8/xmlsec
#8 9.487   copying src/xmlsec/py.typed -> build/lib.linux-x86_64-3.8/xmlsec
#8 9.487   copying src/xmlsec/template.pyi -> build/lib.linux-x86_64-3.8/xmlsec
#8 9.487   copying src/xmlsec/__init__.pyi -> build/lib.linux-x86_64-3.8/xmlsec
#8 9.487   copying src/xmlsec/constants.pyi -> build/lib.linux-x86_64-3.8/xmlsec
#8 9.487   copying src/xmlsec/tree.pyi -> build/lib.linux-x86_64-3.8/xmlsec
#8 9.487   running build_ext
#8 9.487   building 'xmlsec' extension
#8 9.487   creating build/temp.linux-x86_64-3.8
#8 9.487   creating build/temp.linux-x86_64-3.8/tmp
#8 9.487   creating build/temp.linux-x86_64-3.8/tmp/pip-install-_z5f5co9
#8 9.487   creating build/temp.linux-x86_64-3.8/tmp/pip-install-_z5f5co9/xmlsec_43cfa5972a2944a8b155fbf9e117176b
#8 9.487   creating build/temp.linux-x86_64-3.8/tmp/pip-install-_z5f5co9/xmlsec_43cfa5972a2944a8b155fbf9e117176b/src
#8 9.487   gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -D__XMLSEC_FUNCTION__=__func__ -DXMLSEC_NO_SIZE_T -DXMLSEC_NO_GOST=1 -DXMLSEC_NO_GOST2012=1 -DXMLSEC_NO_CRYPTO_DYNAMIC_LOADING=1 -DXMLSEC_CRYPTO_OPENSSL=1 -DMODULE_NAME=xmlsec -DMODULE_VERSION=1.3.10 -I/usr/include/xmlsec1 -I/usr/include/libxml2 -I/tmp/pip-build-env-ryr0mnn_/normal/lib/python3.8/site-packages/lxml/includes -I/tmp/pip-build-env-ryr0mnn_/normal/lib/python3.8/site-packages/lxml -I/tmp/pip-build-env-ryr0mnn_/normal/lib/python3.8/site-packages/lxml/includes/libexslt -I/tmp/pip-build-env-ryr0mnn_/normal/lib/python3.8/site-packages/lxml/includes/__pycache__ -I/tmp/pip-build-env-ryr0mnn_/normal/lib/python3.8/site-packages/lxml/includes/libxslt -I/tmp/pip-build-env-ryr0mnn_/normal/lib/python3.8/site-packages/lxml/includes/libxml -I/usr/local/include/python3.8 -c /tmp/pip-install-_z5f5co9/xmlsec_43cfa5972a2944a8b155fbf9e117176b/src/enc.c -o build/temp.linux-x86_64-3.8/tmp/pip-install-_z5f5co9/xmlsec_43cfa5972a2944a8b155fbf9e117176b/src/enc.o -g -std=c99 -fPIC -fno-strict-aliasing -Wno-error=declaration-after-statement -Werror=implicit-function-declaration -Os
#8 9.487   error: command 'gcc' failed with exit status 1
#8 9.487   ----------------------------------------
#8 9.487   ERROR: Failed building wheel for xmlsec
#8 9.488 Failed to build xmlsec
#8 9.488 ERROR: Could not build wheels for xmlsec which use PEP 517 and cannot be installed directly
------
executor failed running [/bin/sh -c pip install xmlsec]: exit code: 1
```

**Comment by hoefling** [comment]
@andormarkus looks like you're missing the C compiler in the image. `apt install build-essential` before `pip install xmlsec` should resolve this.

**Comment by aalvrz** [comment]
@hoefling I am experiencing a similar issue when installing for Python 3.8 on Amazon AMI system:

I have installed required native libraries listed in README as well as python dev libraries:

```
Collecting xmlsec
  Using cached xmlsec-1.3.10.tar.gz (62 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
    Preparing wheel metadata ... done
Collecting lxml>=3.8
  Using cached lxml-4.6.3-cp38-cp38-manylinux2014_x86_64.whl (6.8 MB)
Building wheels for collected packages: xmlsec
  Building wheel for xmlsec (PEP 517) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/ec2-user/venv/bin/python /home/ec2-user/venv/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py build_wheel /tmp/tmp9t3u4pb_
       cwd: /tmp/pip-install-kj8wrnm5/xmlsec_cba02335d98844c7af359c9f44b996f3
  Complete output (33 lines):
  running bdist_wheel
  running build
  running build_py
  /tmp/pip-build-env-k8r578_h/overlay/lib/python3.8/site-packages/setuptools/dist.py:691: UserWarning: Usage of dash-separated 'description-file' will not be supported in future versions. Please use the underscore name 'description_file' instead
    warnings.warn(
  /tmp/pip-build-env-k8r578_h/overlay/lib/python3.8/site-packages/setuptools/dist.py:691: UserWarning: Usage of dash-separated 'build-requires' will not be supported in future versions. Please use the underscore name 'build_requires' instead
    warnings.warn(
  /tmp/pip-build-env-k8r578_h/overlay/lib/python3.8/site-packages/setuptools/dist.py:691: UserWarning: Usage of dash-separated 'upload-dir' will not be supported in future versions. Please use the underscore name 'upload_dir' instead
    warnings.warn(
  package init file 'src/xmlsec/__init__.py' not found (or not a regular file)
  creating build
  creating build/lib.linux-x86_64-3.8
  creating build/lib.linux-x86_64-3.8/xmlsec
  copying src/xmlsec/py.typed -> build/lib.linux-x86_64-3.8/xmlsec
  copying src/xmlsec/__init__.pyi -> build/lib.linux-x86_64-3.8/xmlsec
  copying src/xmlsec/constants.pyi -> build/lib.linux-x86_64-3.8/xmlsec
  copying src/xmlsec/template.pyi -> build/lib.linux-x86_64-3.8/xmlsec
  copying src/xmlsec/tree.pyi -> build/lib.linux-x86_64-3.8/xmlsec
  running build_ext
  building 'xmlsec' extension
  creating build/temp.linux-x86_64-3.8
  creating build/temp.linux-x86_64-3.8/tmp
  creating build/temp.linux-x86_64-3.8/tmp/pip-install-kj8wrnm5
  creating build/temp.linux-x86_64-3.8/tmp/pip-install-kj8wrnm5/xmlsec_cba02335d98844c7af359c9f44b996f3
  creating build/temp.linux-x86_64-3.8/tmp/pip-install-kj8wrnm5/xmlsec_cba02335d98844c7af359c9f44b996f3/src
  gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -DXMLSEC_CRYPTO_DYNAMIC_LOADING=1 -D__XMLSEC_FUNCTION__=__FUNCTION__ -DXMLSEC_NO_SIZE_T -DXMLSEC_NO_GOST=1 -DXMLSEC_NO_XKMS=1 -DXMLSEC_DL_LIBLTDL=1 -DMODULE_NAME=xmlsec -DMODULE_VERSION=1.3.10 -DXMLSEC_CRYPTO="openssl" -I/usr/include/xmlsec1 -I/usr/include/libxml2 -I/tmp/pip-build-env-k8r578_h/normal/lib64/python3.8/site-packages/lxml/includes -I/tmp/pip-build-env-k8r578_h/normal/lib64/python3.8/site-packages/lxml -I/tmp/pip-build-env-k8r578_h/normal/lib64/python3.8/site-packages/lxml/includes/libxml -I/tmp/pip-build-env-k8r578_h/normal/lib64/python3.8/site-packages/lxml/includes/libxslt -I/tmp/pip-build-env-k8r578_h/normal/lib64/python3.8/site-packages/lxml/includes/libexslt -I/tmp/pip-build-env-k8r578_h/normal/lib64/python3.8/site-packages/lxml/includes/__pycache__ -I/home/ec2-user/venv/include -I/usr/include/python3.8 -c /tmp/pip-install-kj8wrnm5/xmlsec_cba02335d98844c7af359c9f44b996f3/src/constants.c -o build/temp.linux-x86_64-3.8/tmp/pip-install-kj8wrnm5/xmlsec_cba02335d98844c7af359c9f44b996f3/src/constants.o -g -std=c99 -fPIC -fno-strict-aliasing -Wno-error=declaration-after-statement -Werror=implicit-function-declaration -Os
  In file included from /tmp/pip-install-kj8wrnm5/xmlsec_cba02335d98844c7af359c9f44b996f3/src/constants.h:13:0,
                   from /tmp/pip-install-kj8wrnm5/xmlsec_cba02335d98844c7af359c9f44b996f3/src/constants.c:11:
  /tmp/pip-install-kj8wrnm5/xmlsec_cba02335d98844c7af359c9f44b996f3/src/platform.h:16:10: fatal error: Python.h: No such file or directory
   #include <Python.h>
            ^~~~~~~~~~
  compilation terminated.
  error: command 'gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for xmlsec
Failed to build xmlsec
ERROR: Could not build wheels for xmlsec which use PEP 517 and cannot be installed directly

```

**Comment by andormarkus** [comment]
Hi @aalvrz for me `apt install build-essential` solved the problem.

**Comment by aalvrz** [comment]
I don't believe this issue should be closed. `apt install build-essential` might work on Debian but a possible equivalent from Yum will not work:

```shell
yum install make glibc-devel gcc patch
```

😕

**Comment by hoefling** [comment]
@aalvrz `fatal error: Python.h: No such file or directory` indicates you have no Python headers installed. On RHEL and derivatives, the command is `yum install python-devel` or `dnf install python-devel` (or `python3-devel` on older systems still defaulting to Python 2); on Debian and derivatives, the command is `api install python3-dev`.

**Comment by aalvrz** [comment]
@hoefling Thanks for the help. But this seems to be failing specifically for Python 3.8, it works fine with Python 3.7...

**Comment by aalvrz** [comment]
This did the trick:

```
sudo yum install python38-devel
```

🎉
